### ISSUE TITLE
순환 참조가 있는 타입의 필드와 컬렉션 타입 필드가 함께 있을 때 간혈적으로 fixture 생성에 실패함

### ISSUE THREAD

**Issue by ryanproback** [naver/fixture-monkey#1002]
## Describe the bug
* 순환 참조가 있는 타입의 필드를 setNull로 설정하면 (혹은 `.set("fieldName", null)`)
  컬렉션 타입의 필드에 대한 set 메서드가 적용되지 않는 것 같습니다.
* 이것 저것 실험해서 성공하는 케이스도 찾아봤는데요! 하위 링크드린 repo를 참고해주시면 감사하겠습니다.

```java
 @RepeatedTest(100)
  void testFail() {
      FixtureMonkey fixtureMonkey = FixtureMonkey.builder()
                                                 .objectIntrospector(FieldReflectionArbitraryIntrospector.INSTANCE)
                                                 .build();

      // 간혈적인 FixedValueFilterMissException 발생
      TestFailObject actual = fixtureMonkey.giveMeBuilder(TestFailObject.class)
                                           .set("elements", Values.just(new HashSet<>()))
                                           .setNull("referenceTestObjectElement")
                                           .sample();

      assertThat(actual).isNotNull();
  }

  @Getter
  @NoArgsConstructor(access = AccessLevel.PROTECTED)
  static class TestFailObject {
      private Set<TestElement> elements;
      private ReferenceTestObjectElement referenceTestObjectElement;
  }

  @Getter
  @Builder
  static class TestElement {
      private String value;
  }

  @Getter
  @NoArgsConstructor(access = AccessLevel.PROTECTED)
  static class ReferenceTestObjectElement {
      private String value;
      private TestFailObject testFailObject;
  }
```

## Your environment
* correto 17, azul 21
* com.navercorp.fixturemonkey:fixture-monkey-starter:1.0.14
* com.navercorp.fixturemonkey:fixture-monkey-starter:1.0.20

## Steps to reproduce
*Tell us how to reproduce this issue.*
*Or provide us an example repository to check the bug*
- https://github.com/ryanproback/FixtureMonkeyBug/blob/main/src/test/java/com/example/fixturemonkeybug/FixtureMonkeyTest.java

## Expected behaviour
*Tell us what should happen*
- 간혈적인 exception 없이 테스트 성공.

## Actual behaviour
*Tell us what happens instead*
- 간혈적으로 exception이 발생
```
14:38:19.275 [Test worker] WARN  c.n.f.a.i.FieldReflectionArbitraryIntrospector - Given type class com.example.fixturemonkeybug.FixtureMonkeyTest$TestElement is failed to generate due to the exception. It may be null.
java.lang.IllegalArgumentException: The given type class com.example.fixturemonkeybug.FixtureMonkeyTest$TestElement has no matching constructor. parameterTypes: []
	at com.navercorp.fixturemonkey.api.type.TypeCache.lambda$getDeclaredConstructor$6(TypeCache.java:128)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at com.navercorp.fixturemonkey.api.type.TypeCache.getDeclaredConstructor(TypeCache.java:125)
	at com.navercorp.fixturemonkey.api.introspector.FieldReflectionArbitraryIntrospector.checkPrerequisite(FieldReflectionArbitraryIntrospector.java:83)
	at com.navercorp.fixturemonkey.api.introspector.FieldReflectionArbitraryIntrospector.introspect(FieldReflectionArbitraryIntrospector.java:63)
	at com.navercorp.fixturemonkey.api.introspector.MatchArbitraryIntrospector.introspect(MatchArbitraryIntrospector.java:63)
	at com.navercorp.fixturemonkey.api.generator.IntrospectedArbitraryGenerator.generate(IntrospectedArbitraryGenerator.java:64)
	at com.navercorp.fixturemonkey.api.generator.MatchArbitraryGenerator.generate(MatchArbitraryGenerator.java:53)
	at com.navercorp.fixturemonkey.api.generator.CompositeArbitraryGenerator.generate(CompositeArbitraryGenerator.java:52)
	at com.navercorp.fixturemonkey.tree.ObjectTree.generateIntrospected(ObjectTree.java:154)
	at com.navercorp.fixturemonkey.tree.ObjectTree.lambda$generateContext$1(ObjectTree.java:126)
	at com.navercorp.fixturemonkey.api.generator.ArbitraryGeneratorContext.initArbitraryListByArbitraryProperty(ArbitraryGeneratorContext.java:163)
	at com.navercorp.fixturemonkey.api.lazy.UnSafeLazyArbitraryImpl.getValue(UnSafeLazyArbitraryImpl.java:53)
	at com.navercorp.fixturemonkey.api.generator.ArbitraryGeneratorContext.getElementCombinableArbitraryList(ArbitraryGeneratorContext.java:124)
	at com.navercorp.fixturemonkey.api.introspector.SetIntrospector.introspect(SetIntrospector.java:59)
	at com.navercorp.fixturemonkey.api.introspector.MatchArbitraryIntrospector.introspect(MatchArbitraryIntrospector.java:57)
	at com.navercorp.fixturemonkey.api.introspector.MatchArbitraryIntrospector.introspect(MatchArbitraryIntrospector.java:63)
	at com.navercorp.fixturemonkey.api.generator.IntrospectedArbitraryGenerator.generate(IntrospectedArbitraryGenerator.java:64)
	at com.navercorp.fixturemonkey.api.generator.MatchArbitraryGenerator.generate(MatchArbitraryGenerator.java:53)
	at com.navercorp.fixturemonkey.api.generator.CompositeArbitraryGenerator.generate(CompositeArbitraryGenerator.java:52)
	at com.navercorp.fixturemonkey.tree.ObjectTree.generateIntrospected(ObjectTree.java:154)
	at com.navercorp.fixturemonkey.tree.ObjectTree.lambda$generateContext$1(ObjectTree.java:126)
	at com.navercorp.fixturemonkey.api.generator.ArbitraryGeneratorContext.initArbitraryListByArbitraryProperty(ArbitraryGeneratorContext.java:163)
	at com.navercorp.fixturemonkey.api.lazy.UnSafeLazyArbitraryImpl.getValue(UnSafeLazyArbitraryImpl.java:53)
	at com.navercorp.fixturemonkey.api.generator.ArbitraryGeneratorContext.getCombinableArbitrariesByArbitraryProperty(ArbitraryGeneratorContext.java:109)
	at com.navercorp.fixturemonkey.api.introspector.FieldReflectionArbitraryIntrospector.introspect(FieldReflectionArbitraryIntrospector.java:58)
	at com.navercorp.fixturemonkey.api.introspector.MatchArbitraryIntrospector.introspect(MatchArbitraryIntrospector.java:63)
	at com.navercorp.fixturemonkey.api.generator.IntrospectedArbitraryGenerator.generate(IntrospectedArbitraryGenerator.java:64)
	at com.navercorp.fixturemonkey.api.generator.MatchArbitraryGenerator.generate(MatchArbitraryGenerator.java:53)
	at com.navercorp.fixturemonkey.api.generator.CompositeArbitraryGenerator.generate(CompositeArbitraryGenerator.java:52)
	at com.navercorp.fixturemonkey.tree.ObjectTree.generateIntrospected(ObjectTree.java:154)
	at com.navercorp.fixturemonkey.tree.ObjectTree.lambda$generateContext$1(ObjectTree.java:126)
	at com.navercorp.fixturemonkey.api.generator.ArbitraryGeneratorContext.initArbitraryListByArbitraryProperty(ArbitraryGeneratorContext.java:163)
	at com.navercorp.fixturemonkey.api.lazy.UnSafeLazyArbitraryImpl.getValue(UnSafeLazyArbitraryImpl.java:53)
	at com.navercorp.fixturemonkey.api.generator.ArbitraryGeneratorContext.getCombinableArbitrariesByArbitraryProperty(ArbitraryGeneratorContext.java:109)
	at com.navercorp.fixturemonkey.api.introspector.FieldReflectionArbitraryIntrospector.introspect(FieldReflectionArbitraryIntrospector.java:58)
	at com.navercorp.fixturemonkey.api.introspector.MatchArbitraryIntrospector.introspect(MatchArbitraryIntrospector.java:63)
	at com.navercorp.fixturemonkey.api.generator.IntrospectedArbitraryGenerator.generate(IntrospectedArbitraryGenerator.java:64)
	at com.navercorp.fixturemonkey.api.generator.MatchArbitraryGenerator.generate(MatchArbitraryGenerator.java:53)
	at com.navercorp.fixturemonkey.api.generator.CompositeArbitraryGenerator.generate(CompositeArbitraryGenerator.java:52)
	at com.navercorp.fixturemonkey.tree.ObjectTree.generateIntrospected(ObjectTree.java:154)
	at com.navercorp.fixturemonkey.tree.ObjectTree.lambda$generateContext$1(ObjectTree.java:126)
	at com.navercorp.fixturemonkey.api.generator.ArbitraryGeneratorContext.initArbitraryListByArbitraryProperty(ArbitraryGeneratorContext.java:163)
	at com.navercorp.fixturemonkey.api.lazy.UnSafeLazyArbitraryImpl.getValue(UnSafeLazyArbitraryImpl.java:53)
	at com.navercorp.fixturemonkey.api.generator.ArbitraryGeneratorContext.getCombinableArbitrariesByArbitraryProperty(ArbitraryGeneratorContext.java:109)
	at com.navercorp.fixturemonkey.api.introspector.FieldReflectionArbitraryIntrospector.introspect(FieldReflectionArbitraryIntrospector.java:58)
	at com.navercorp.fixturemonkey.api.introspector.MatchArbitraryIntrospector.introspect(MatchArbitraryIntrospector.java:63)
	at com.navercorp.fixturemonkey.api.generator.IntrospectedArbitraryGenerator.generate(IntrospectedArbitraryGenerator.java:64)
	at com.navercorp.fixturemonkey.api.generator.MatchArbitraryGenerator.generate(MatchArbitraryGenerator.java:53)
	at com.navercorp.fixturemonkey.api.generator.CompositeArbitraryGenerator.generate(CompositeArbitraryGenerator.java:52)
	at com.navercorp.fixturemonkey.tree.ObjectTree.generateIntrospected(ObjectTree.java:154)
	at com.navercorp.fixturemonkey.tree.ObjectTree.generate(ObjectTree.java:93)
	at com.navercorp.fixturemonkey.resolver.ArbitraryResolver.lambda$resolve$2(ArbitraryResolver.java:120)
	at com.navercorp.fixturemonkey.resolver.ResolvedCombinableArbitrary.lambda$new$0(ResolvedCombinableArbitrary.java:64)
	at com.navercorp.fixturemonkey.api.lazy.UnSafeLazyArbitraryImpl.getValue(UnSafeLazyArbitraryImpl.java:53)
	at com.navercorp.fixturemonkey.resolver.ResolvedCombinableArbitrary.combined(ResolvedCombinableArbitrary.java:75)
	at com.navercorp.fixturemonkey.resolver.DefaultArbitraryBuilder.sample(DefaultArbitraryBuilder.java:489)
	at com.example.fixturemonkeybug.FixtureMonkeyTest.testFail(FixtureMonkeyTest.java:31)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:94)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:218)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:214)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:139)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:142)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:110)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:110)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:44)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:119)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:94)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:89)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

ps: 좋은 라이브러리 덕에 편하게 테스트를 보강하고 있습니다. 감사합니다!

**Comment by seongahjo** [comment]
@ryanproback 
안녕하세요.

지금 보여주신 케이스에서 기본 생성 방법으로 사용하는 `FieldRefletionArbitraryIntrospector` 는 빈 생성자가 필요한 생성 방법입니다.
생성하려는 `TestElement` 타입이 빈 생성자가 없어 예외가 발생한 것으로 보입니다.

이 문제를 해결하는 방법에는 두 가지가 있는데요.

첫 번째는 ArbitraryBuilder의 연산을 사용하는 방법입니다.

`setNull` 연산은 예외가 발생하지 않은 경우에 null로 세팅하는 연산입니다. 지금 같은 경우에서는 referenceTestObjectElement를 생성하다가 예외가 발생하므로 의도대로 동작하지 않은 걸로 보입니다.

다음과 같이 사용하면 예외가 발생하더라도 null로 세팅할 수 있습니다.
`set("referenceTestObjectElement", Values.just(null))` 

두 번째는 TestElement 타입을 생성하는 방법을 지정해주는 옵션을 사용하는 방법입니다.

`pushArbitraryIntrospector`로 `TestElement`를 생성하는 다른 ArbitraryIntrospector를 설정하시면 이슈가 해결될 것으로 보입니다.
ex. `pushAssignableTypeArbitraryIntrospector(TestElement.class, BuilderArbitraryIntrosepctor.INSTANCE)`


감사합니다.

**Comment by seongahjo** [comment]
@ryanproback 
두 연산이 다른데요, `set`은 생성을 하지않고 `setNull`은 생성을 합니다.

이유는 `setNull` 이후 다른 연산들이 올 수 있기 때문입니다. 이때 `setNull`의 연산의 결과는 무시됩니다.
다음 대표적으로 두 가지 경우의 수가 있을 수 있습니다.
1. `setNull` 이후에 `setNotNull`을 호출하는 경우.
2. `setNull`을 실행한 타입의 필드를 `set`하는 경우

2번의 예를 들면 다음 연산이 있으면 setNull의 결과는 무시되고 a의 b는 "b"로 생성됩니다.
```
.setNull("a")
.set("a.b", "b")
```

혹시 추가적으로 궁금하신 점 있으시면 편하게 물어봐주세요!

**Comment by ryanproback** [comment]
감사합니다!
