### ISSUE TITLE
Error when using Fixture Monkey Plugin

### ISSUE THREAD

**Issue by eastglow** [naver/fixture-monkey#1070]
## Describe the bug
안녕하세요. Fixture Monkey IntelliJ Plugin을 설치 후 사용 중인데 간헐적으로 아래 내용과 같은 인텔리제이 에러 리포트가 떠서 이슈 남깁니다.

## Your environment
* plugin 0.0.13
* <img width="462" alt="image" src="https://github.com/user-attachments/assets/ea0cd1c6-b876-40f0-9170-d812dd6d1075">

## Steps to reproduce
* 어느 동작에서 재현되는지는 정확히 알 수 없고 인텔리제이 사용중 혹은 재시작 후에 한번씩 에러창이 뜨곤 합니다.
```
java.lang.IllegalArgumentException: Invalid range specified: (1, 0); 
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:288)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:283)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:279)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:42)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:31)
	at org.monkeyhelper.plugins.language.java.reference.MonkeyExpressionJavaReferenceContributor$registerReferenceProviders$1.getReferencesByElement(MonkeyExpressionJavaReferenceContributor.kt:51)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:162)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:143)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:122)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:44)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:173)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.kt:40)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:236)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.kt:34)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:170)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:42)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:32)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:25)
	at com.intellij.psi.PsiReferenceService.getContributedReferences(PsiReferenceService.java:33)
	at com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl.getReferences(PsiLiteralExpressionImpl.java:189)
	at com.intellij.codeInsight.daemon.impl.analysis.LocalRefUseInfo$Builder.visitLiteralExpression(LocalRefUseInfo.java:383)
	at com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl.accept(PsiLiteralExpressionImpl.java:168)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:58)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:11)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:63)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:40)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:67)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:41)
	at com.intellij.codeInsight.daemon.impl.analysis.LocalRefUseInfo$Builder.visitElement(LocalRefUseInfo.java:295)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:51)
	at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:225)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:542)
	at com.intellij.codeInsight.daemon.impl.analysis.LocalRefUseInfo.lambda$forFile$0(LocalRefUseInfo.java:47)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:173)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.kt:40)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:236)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.kt:34)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:170)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.codeInsight.daemon.impl.analysis.LocalRefUseInfo.forFile(LocalRefUseInfo.java:44)
	at com.siyeh.ig.psiutils.VariableAccessUtils.variableIsUsed(VariableAccessUtils.java:317)
	at com.intellij.codeInspection.dataFlow.StandardDataFlowRunner.lambda$forNestedClosures$3(StandardDataFlowRunner.java:238)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:390)
	at one.util.streamex.AbstractStreamEx.toMutableList(AbstractStreamEx.java:1345)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1326)
	at com.intellij.codeInspection.dataFlow.StandardDataFlowRunner.forNestedClosures(StandardDataFlowRunner.java:239)
	at com.intellij.codeInspection.dataFlow.StandardDataFlowRunner.analyzeBlockRecursively(StandardDataFlowRunner.java:218)
	at com.intellij.codeInspection.dataFlow.StandardDataFlowRunner.analyzeMethodRecursively(StandardDataFlowRunner.java:208)
	at com.intellij.codeInspection.dataFlow.CommonDataflow.runDFA(CommonDataflow.java:249)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.codeInspection.dataFlow.CommonDataflow$1ManagedCompute.block(CommonDataflow.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3977)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3959)
	at com.intellij.codeInspection.dataFlow.CommonDataflow.getDataflowResult(CommonDataflow.java:306)
	at com.intellij.codeInspection.dataFlow.CommonDataflow.getDfType(CommonDataflow.java:335)
	at com.intellij.codeInspection.dataFlow.CommonDataflow.getDfType(CommonDataflow.java:325)
	at com.intellij.codeInspection.dataFlow.NullabilityUtil.getExpressionNullability(NullabilityUtil.java:127)
	at com.intellij.codeInsight.daemon.impl.quickfix.WrapObjectWithOptionalOfNullableFix.getModifiedExpression(WrapObjectWithOptionalOfNullableFix.java:129)
	at com.intellij.codeInsight.daemon.impl.quickfix.WrapObjectWithOptionalOfNullableFix$MyFixerActionFactory.getModifiedArgument(WrapObjectWithOptionalOfNullableFix.java:93)
	at com.intellij.codeInsight.daemon.impl.quickfix.ArgumentFixerActionFactory.replaceWithCast(ArgumentFixerActionFactory.java:144)
	at com.intellij.codeInsight.daemon.impl.quickfix.ArgumentFixerActionFactory.registerCastActions(ArgumentFixerActionFactory.java:90)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.registerMethodCallIntentions(HighlightMethodUtil.java:1099)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.checkAmbiguousMethodCallArguments(HighlightMethodUtil.java:1023)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitExpressionList(HighlightVisitorImpl.java:655)
	at com.intellij.psi.impl.source.tree.java.PsiExpressionListImpl.accept(PsiExpressionListImpl.java:159)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:165)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.runVisitor(HighlightVisitorRunner.java:196)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.lambda$runVisitors$3(HighlightVisitorRunner.java:122)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:176)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.lambda$runVisitors$4(HighlightVisitorRunner.java:120)
	at com.intellij.concurrency.ApplierCompleter.processArrayItem(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.processArray(ApplierCompleter.java:196)
	at com.intellij.concurrency.ApplierCompleter.execAll(ApplierCompleter.java:166)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgressAsync$3(JobLauncherImpl.java:103)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:279)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$2(ApplierCompleter.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapAndRun$1(ApplierCompleter.java:140)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.wrapAndRun(ApplierCompleter.java:140)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgressAsync$4(JobLauncherImpl.java:103)
	at com.intellij.concurrency.JobLauncherImpl.safeIterate(JobLauncherImpl.java:168)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgressAsync(JobLauncherImpl.java:100)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:48)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:51)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.runVisitors(HighlightVisitorRunner.java:112)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$15(GeneralHighlightingPass.java:247)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgressAsync(JobLauncherImpl.java:97)
	at com.intellij.concurrency.JobLauncherImpl.processConcurrentlyAsync(JobLauncherImpl.java:465)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotatorsAsync(AnnotatorRunner.java:67)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:257)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectInformationWithProgress$12(GeneralHighlightingPass.java:190)
	at com.intellij.codeInsight.daemon.impl.HighlightInfoUpdaterImpl.lambda$runWithInvalidPsiRecycler$32(HighlightInfoUpdaterImpl.java:689)
	at com.intellij.codeInsight.daemon.impl.ManagedHighlighterRecycler.runWithRecycler(ManagedHighlighterRecycler.java:87)
	at com.intellij.codeInsight.daemon.impl.HighlightInfoUpdaterImpl.runWithInvalidPsiRecycler(HighlightInfoUpdaterImpl.java:671)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectInformationWithProgress$13(GeneralHighlightingPass.java:215)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.createHighlightVisitorsFor(HighlightVisitorRunner.java:84)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:112)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:86)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:426)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:417)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:416)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:392)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:392)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:390)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:259)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

```

**Comment by seongahjo** [comment]
@eastglow 님 안녕하세요.

플러그인을 만들고 계신 분들께 이슈 레포트 하겠습니다.
공유 감사합니다!

**Comment by seongahjo** [comment]
오랜 기간 추가 응답이 없어 이 이슈를 자동으로 종료합니다.
문제가 계속되거나 추가 논의가 필요하시면 언제든 코멘트를 남겨주세요. 다시 열어 도와드리겠습니다.
감사합니다.
