### ISSUE TITLE
1.1.1 버전 kotlin register 사용 방법

### ISSUE THREAD

**Issue by jurogrammer** [naver/fixture-monkey#1085]
## Describe your question
1.1.1 버전에서 Kotlin ArbitraryBuilder 타입이 새로 생긴 걸로 이해했습니다.

다만, register에서는 `DefaultArbitraryBuilder`를 등록하기 때문에 giveMeKotlinBuilder를 사용한 경우 ClassCastException이 발생합니다.

혹시 제가 놓친 업데이트 사항이 있을까요?

감사합니다.

```kotlin
 FixtureMonkey
            .builder()
            .register { fixtureMonkey ->
                fixtureMonkey.giveMeKotlinBuilder<Product>()
                    .set(Product::createdBy, "testUpdatedBy")
            }
            .build()
```

```
java.lang.ClassCastException: Cannot cast com.navercorp.fixturemonkey.kotlin.KotlinTypeDefaultArbitraryBuilder to com.navercorp.fixturemonkey.builder.DefaultArbitraryBuilder
	at java.base/java.lang.Class.cast(Class.java:3889)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.navercorp.fixturemonkey.FixtureMonkey.giveMeBuilder(FixtureMonkey.java:91)
```

**Comment by seongahjo** [comment]
@jurogrammer 님 안녕하세요.

1.1.2 배포해서 공유드립니다.
혹시 문제가 해결 안됐으면 말씀해주세요.

감사합니다.

**Comment by jurogrammer** [comment]
@seongahjo 안녕하세요~
감사합니다. 정상 동작 확인했습니다!
