### ISSUE TITLE
Failed to generate fixtures for Kotlin sealed class containing object declaration due to missing primary constructor

### ISSUE THREAD

**Issue by forgreen0624** [naver/fixture-monkey#1132]
## Describe the bug
When using the FixtureMonkey library to generate fixtures for a Kotlin sealed class, the process fails if the sealed class contains an `object` declaration. The error message indicates that a primary constructor is not provided for the `object` class, which leads to fixture generation failure.

## Your environment
* version of Fixture Monkey: 1.1.6
* version of Java/Kotlin : kotlin, 2.0.20

## Steps to reproduce
```kotlin
class FixtureMonkeyTest {

    @Test
    fun `test fixtureMonkey`() {
        val sampled = FixtureMonkeyBuilder()
            .plugin(KotlinPlugin())
            .build()
            .giveMeKotlinBuilder<MyData>()
            .set(MyData::name, "my_name")
            .sample()

        println("sampled: $sampled")

    }

    data class MyData(
        val id: Int,
        val name: String,
        val scheme: Scheme,
    )

    sealed class Scheme {
        data class Url(val scheme: String) : Scheme()
        data object None : Scheme()
    }
}
```

## Expected behaviour
scheme property in `MyData` class could be initialized with arbitrarily one of `Scheme.Url(String)`. `Scheme.None`

## Actual behaviour
```
No kotlin primary constructor provided for class com.fixturetest.FixtureMonkeyTest$Scheme$None
java.lang.IllegalArgumentException: No kotlin primary constructor provided for class com.fixturetest.FixtureMonkeyTest$Scheme$None
	at com.navercorp.fixturemonkey.kotlin.type.KotlinTypeCacheKt$kotlinPrimaryConstructor$1.invoke(KotlinTypeCache.kt:51)
	at com.navercorp.fixturemonkey.kotlin.type.KotlinTypeCacheKt$kotlinPrimaryConstructor$1.invoke(KotlinTypeCache.kt:49)
	at com.navercorp.fixturemonkey.kotlin.type.KotlinTypeCacheKt.kotlinPrimaryConstructor$lambda$4(KotlinTypeCache.kt:49)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at com.navercorp.fixturemonkey.kotlin.type.KotlinTypeCacheKt.kotlinPrimaryConstructor(KotlinTypeCache.kt:49)
	at com.navercorp.fixturemonkey.kotlin.introspector.PrimaryConstructorArbitraryIntrospector$Companion$PROPERTY_GENERATOR$1.invoke(PrimaryConstructorArbitraryIntrospector.kt:87)
	at com.navercorp.fixturemonkey.kotlin.introspector.PrimaryConstructorArbitraryIntrospector$Companion$PROPERTY_GENERATOR$1.invoke(PrimaryConstructorArbitraryIntrospector.kt:86)
	at com.navercorp.fixturemonkey.kotlin.property.KotlinConstructorParameterPropertyGenerator$generateChildProperties$1.invoke(KotlinConstructorParameterPropertyGenerator.kt:45)
	at com.navercorp.fixturemonkey.kotlin.property.KotlinConstructorParameterPropertyGenerator$generateChildProperties$1.invoke(KotlinConstructorParameterPropertyGenerator.kt:44)
	at com.navercorp.fixturemonkey.kotlin.property.KotlinConstructorParameterPropertyGenerator.generateChildProperties$lambda$0(KotlinConstructorParameterPropertyGenerator.kt:44)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at com.navercorp.fixturemonkey.kotlin.property.KotlinConstructorParameterPropertyGenerator.generateChildProperties(KotlinConstructorParameterPropertyGenerator.kt:44)
	at com.navercorp.fixturemonkey.api.property.CompositePropertyGenerator.generateChildProperties(CompositePropertyGenerator.java:57)
	at com.navercorp.fixturemonkey.builder.ArbitraryBuilderContext.lambda$initializeResolvedPropertyGenerator$2(ArbitraryBuilderContext.java:310)
	at com.navercorp.fixturemonkey.api.property.LazyPropertyGenerator.lambda$null$0(LazyPropertyGenerator.java:50)
	at com.navercorp.fixturemonkey.api.lazy.UnSafeLazyArbitraryImpl.getValue(UnSafeLazyArbitraryImpl.java:53)
	at com.navercorp.fixturemonkey.api.property.LazyPropertyGenerator.generateChildProperties(LazyPropertyGenerator.java:51)
	at com.navercorp.fixturemonkey.api.tree.TreeProperty.lambda$toArbitraryProperty$0(TreeProperty.java:85)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.navercorp.fixturemonkey.api.tree.TreeProperty.toArbitraryProperty(TreeProperty.java:87)
	at com.navercorp.fixturemonkey.api.tree.DefaultTraverseNode.generateObjectNode(DefaultTraverseNode.java:335)
	at com.navercorp.fixturemonkey.api.tree.DefaultTraverseNode.generateChildrenNodes(DefaultTraverseNode.java:464)
	at com.navercorp.fixturemonkey.api.tree.DefaultTraverseNode.lambda$expand$1(DefaultTraverseNode.java:230)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.navercorp.fixturemonkey.api.tree.DefaultTraverseNode.expand(DefaultTraverseNode.java:239)
	at com.navercorp.fixturemonkey.tree.ObjectNode.expand(ObjectNode.java:70)
	at com.navercorp.fixturemonkey.tree.MetadataCollector.collect(MetadataCollector.java:66)
	at com.navercorp.fixturemonkey.tree.MetadataCollector.collect(MetadataCollector.java:54)
	at com.navercorp.fixturemonkey.tree.ObjectTree.<init>(ObjectTree.java:48)
	at com.navercorp.fixturemonkey.resolver.ArbitraryResolver.lambda$resolve$2(ArbitraryResolver.java:69)
	at com.navercorp.fixturemonkey.api.lazy.UnSafeLazyArbitraryImpl.getValue(UnSafeLazyArbitraryImpl.java:53)
	at com.navercorp.fixturemonkey.resolver.ResolvedCombinableArbitrary.lambda$new$0(ResolvedCombinableArbitrary.java:63)
	at com.navercorp.fixturemonkey.api.lazy.UnSafeLazyArbitraryImpl.getValue(UnSafeLazyArbitraryImpl.java:53)
	at com.navercorp.fixturemonkey.resolver.ResolvedCombinableArbitrary.combined(ResolvedCombinableArbitrary.java:75)
	at com.navercorp.fixturemonkey.builder.DefaultArbitraryBuilder.sample(DefaultArbitraryBuilder.java:483)
	at com.navercorp.fixturemonkey.kotlin.KotlinTypeDefaultArbitraryBuilder.sample(FixtureMonkeyExtensions.kt:245)
	at com.fixturetest.FixtureMonkeyTest.test fixtureMonkey(FixtureMonkeyTest.kt:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:54)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
	at jdk.proxy1/jdk.proxy1.$Proxy4.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:181)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:130)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:101)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:61)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:122)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by seongahjo** [comment]
@forgreen0624 
Hi.

I cannot reproduce the case. Can you check it if it is the right case?

<img width="469" alt="image" src="https://github.com/user-attachments/assets/b7f14b0d-a545-418f-a888-4ab4afc09c35" />

Thank you.

**Comment by manikoske** [comment]
I have the very same issue with the very same code. What do you mean by checking if it is the right case? I have even tried to set the value for scheme explicitly, however I got the same issue. 

Is there any workaround?



    sealed class Scheme {
        data class Url(val scheme: String) : Scheme()
        data object None : Scheme()
    }

    data class MyData(
        val id: Int,
        val name: String,
        val scheme: Scheme,
    )

    @Test
    fun test fixtureMonkey() {
        val sampled = FixtureMonkeyBuilder()
            .plugin(KotlinPlugin())
            .build()
            .giveMeKotlinBuilder<MyData>()
            .set(MyData::scheme, Scheme.None) // new line of code
            .sample()

        println("sampled: $sampled")
    }

**Comment by seongahjo** [comment]
@manikoske 
This means that the following example cannot reproduce the problem.
It helps if you give me the deterministic example that always gives the same result.
It could be non-deterministic, in which case you must give me the seed to reproduce.

> Also I have a side question. Is there any way to register a FixtureMonkey wide rule to always create the Scheme class the same way, for example always to be set to None?

In this case, the easiest way is to use the `pushAssignableTypeArbitraryIntrospector'.

```kotlin
FixtureMonkey.builder()
    .pushAssignableTypeArbitraryIntrospector<Scheme> {
        ArbitraryIntrospectorResult(CombinableArbitrary.from(Scheme.None))
    }
.build()
```

**Comment by manikoske** [comment]
Thank you for your quick response. I have run the test thousands of times and for each iteration the result was the same. 

Neither this:

```
    @Test
    fun fixtureMonkey() {
        val sampled = FixtureMonkeyBuilder()
            .plugin(KotlinPlugin())
            .pushAssignableTypeArbitraryIntrospector<Scheme> {
                ArbitraryIntrospectorResult(CombinableArbitrary.from(Scheme.None))
            }
            .build()
            .giveMeKotlinBuilder<MyData>()
            .sample()

        println("sampled: $sampled")
    }
```
or this:
```
    @Test
    fun fixtureMonkey() {
        val sampled = FixtureMonkeyBuilder()
            .plugin(KotlinPlugin())
            .build()
            .giveMeKotlinBuilder<MyData>()
            .set(MyData::scheme, Values.just(Scheme.None)) // new line of code
            .sample()

        println("sampled: $sampled")
    }

```
Every time I get the same exception:
```
java.lang.IllegalArgumentException: No kotlin primary constructor provided for class Scheme$None
```

Also, another side question. I cant seem to find information about pushAssignableTypeArbitraryIntrospector nor any information about seeding. Can you point me to the right source? Thank you.

**Comment by nitinjangid091999** [comment]
Hey @seongahjo,

I'm encountering the same error when using a sealed class with Kotlin objects. It seems to occur only when all the children of the sealed class are objects.

Could you take a look at the example below and let me know your thoughts?

Version of Fixture Monkey: 1.1.9
Version of Kotlin: 2.0.0

`class UserUnitTest {
  @Test
  fun user_isCorrect() {
    val sut = FixtureMonkey.builder()
      .plugin(KotlinPlugin())
      .build()

    sut.giveMeKotlinBuilder<User>()
      .sample()
  }
}


data class User(
  val name: String,
  val country: Country,
)

sealed class Country(name: String) {
  object USA : Country("United States")
  object UAE : Country("United Arab Emirates")
}

`

**Comment by nitinjangid091999** [comment]
Hey @seongahjo,

Thanks for your response.

Why is your test case failing with the error ?
```java.lang.IllegalArgumentException: bound must be positive```

Can you please tell me the reason, if possible ?

**Comment by seongahjo** [comment]
@nitinjangid091999 
This is because currently the `sealed object` is now filtered as below.
It is not the generate target because of its constant, but it will be in the near future.

<img width="617" alt="Image" src="https://github.com/user-attachments/assets/6d134fab-bcb4-45a8-9b3a-cfb91b53ac91" />

To address this issue, I need to find the test case to reproduce the following exception to avoid the regression.

`No kotlin primary constructor provided for class com.fixturetest.FixtureMonkeyTest$Scheme$None`

**Comment by nitinjangid091999** [comment]
@seongahjoIs 
Is there a workaround to resolve this issue on my end, such as passing the object manually instead of allowing the library to create it?

I tried something like the below, but it didn't work. It's the same issue I was getting.

```
FixtureMonkey.builder()
    .pushAssignableTypeArbitraryIntrospector<Scheme> {
        ArbitraryIntrospectorResult(CombinableArbitrary.from(Country.UAE))
    }
.build()
```

Thanks

**Comment by seongahjo** [comment]
@nitinjangid091999 
> Is there a workaround to resolve this issue on my end, such as passing the object manually instead of allowing the library to create it?

Could you check if the issue is fixed in `1.1.10`?
Since I cannot reproduce the issue, I cannot check if it is fixed.

**Comment by nitinjangid091999** [comment]
@seongahjo 
I have checked with 1.1.10, and now I am getting the below error 
`java.lang.IllegalArgumentException: bound must be positive`

**Comment by seongahjo** [comment]
@nitinjangid091999 
Well... I need the public git repository that can reproduce the issue.

**Comment by forgreen0624** [comment]
@seongahjo 
I apologize for the delay in my response.

We were able to reproduce the issue in the Android project. I have uploaded a public repository containing the project that reproduces the issue.


## Reproduction environment

> Kotlin version: 2.0.21
> FixtureMonkey version: 1.1.10
> Repository: https://github.com/forgreen0624/fixture-monkey-issue-reproduction/tree/main

Since Android is configured to use JUnit 4 by default, I conducted the reproduction test using JUnit 4.
JUnit 4 reproduction test case: https://github.com/forgreen0624/fixture-monkey-issue-reproduction/blob/main/app/src/test/java/com/example/fixture_monkey_bug_reproduction/reproduction/SchemeTest.kt

I have also reproduced the issue using JUnit 5.
JUnit 5 reproduction test case: https://github.com/forgreen0624/fixture-monkey-issue-reproduction/blob/main/reproduction/junit5/src/test/java/com/example/junit5/reproduction/MyDataTest.kt


Note: After upgrading FixtureMonkey to the latest version (1.1.10), the issue now displays a different description— `java.lang.IllegalArgumentException: bound must be positive`—compared to the previous version.

<img width="2032" alt="Image" src="https://github.com/user-attachments/assets/9e0370e1-8efe-4f47-946e-fc55ee888753" />


In addition, it appears that this issue occurs when a sealed class’s subclasses consist solely of objects. Unlike FixtureMonkey’s previous version (v1.1.6), the latest version (v1.10.0) seems to exclude object classes when they are mixed with other classes during generation.

When writing the reproduction test cases, I created separate cases for scenarios where a sealed class contains a mix of object and non-object classes, and where it contains only object classes.

**Comment by seongahjo** [comment]
@forgreen0624 
Hello, thank you for providing an example to reproduce the issue.

I am trying to fix the issue in `1.1.11`, please check it if the issue is fixed.


Thank you

cc @nitinjangid091999

**Comment by seongahjo** [comment]
Closing this issue automatically due to no further response.
If the problem still persists or you'd like to continue the discussion, please leave a comment and we'll be happy to reopen it.
Thank you!
