### ISSUE TITLE
Unsupported Type to get actualType. type: class sun.reflect.generics.reflectiveObjects.GenericArrayTypeImpl

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#604]
## Describe the bug
I will be only able to create a reproduction in a week or so but what I did was basically create a [jOOQ Custom Record](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/CustomRecord.html).

And then `fixtureMonkey.giveMeOne(MyCustomRecord.class);`

## Your environment
* Fixture Monkey: 0.5.2
* Java 17

## Steps to reproduce
`//TODO`

## Expected behaviour
Should just work

## Actual behaviour
```
java.lang.UnsupportedOperationException: Unsupported Type to get actualType. type: class sun.reflect.generics.reflectiveObjects.GenericArrayTypeImpl
	at com.navercorp.fixturemonkey.api.type.Types.getActualType(Types.java:106)
	at com.navercorp.fixturemonkey.api.matcher.ExactTypeMatcher.match(ExactTypeMatcher.java:37)
	at com.navercorp.fixturemonkey.api.matcher.MatcherOperator.match(MatcherOperator.java:46)
	at com.navercorp.fixturemonkey.api.option.GenerateOptions.lambda$getContainerPropertyGenerator$2(GenerateOptions.java:194)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.navercorp.fixturemonkey.api.option.GenerateOptions.getContainerPropertyGenerator(GenerateOptions.java:196)
	at com.navercorp.fixturemonkey.resolver.ArbitraryTraverser.generateChildrenNodes(ArbitraryTraverser.java:190)
	at com.navercorp.fixturemonkey.resolver.ArbitraryTraverser.traverse(ArbitraryTraverser.java:155)
	at com.navercorp.fixturemonkey.resolver.ArbitraryTraverser.generateChildrenNodes(ArbitraryTraverser.java:252)
	at com.navercorp.fixturemonkey.resolver.ArbitraryTraverser.traverse(ArbitraryTraverser.java:155)
	at com.navercorp.fixturemonkey.resolver.ArbitraryTraverser.generateChildrenNodes(ArbitraryTraverser.java:252)
	at com.navercorp.fixturemonkey.resolver.ArbitraryTraverser.traverse(ArbitraryTraverser.java:155)
	at com.navercorp.fixturemonkey.resolver.ArbitraryTraverser.traverse(ArbitraryTraverser.java:109)
	at com.navercorp.fixturemonkey.resolver.ArbitraryResolver.resolve(ArbitraryResolver.java:74)
	at com.navercorp.fixturemonkey.resolver.DefaultArbitraryBuilder.lambda$build$7(DefaultArbitraryBuilder.java:407)
	at com.navercorp.fixturemonkey.resolver.ArbitraryValue$MonkeyRandomGenerator.getArbitrary(ArbitraryValue.java:142)
	at com.navercorp.fixturemonkey.resolver.ArbitraryValue$MonkeyRandomGenerator.next(ArbitraryValue.java:94)
	at net.jqwik.engine.facades.SampleStreamFacade.lambda$sampleStream$2(SampleStreamFacade.java:68)
	at net.jqwik.engine.execution.lifecycle.CurrentTestDescriptor.runWithDescriptor(CurrentTestDescriptor.java:17)
	at net.jqwik.engine.facades.SampleStreamFacade.runInDescriptor(SampleStreamFacade.java:60)
	at net.jqwik.engine.facades.SampleStreamFacade.lambda$wrapInDescriptor$1(SampleStreamFacade.java:55)
	at java.base/java.util.stream.StreamSpliterators$InfiniteSupplyingSpliterator$OfRef.tryAdvance(StreamSpliterators.java:1358)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.navercorp.fixturemonkey.FixtureMonkey.giveMe(FixtureMonkey.java:166)
	at com.navercorp.fixturemonkey.FixtureMonkey.giveMeOne(FixtureMonkey.java:174)
```

**Comment by esfomeado** [comment]
Replication: https://github.com/esfomeado/fixture-monkey-bug/blob/ad6ccbd7c841501c42ce8dc0edaaeb1be1328110/src/test/java/com/example/bug/FixtureMonkeyTest.java#LL24C13-L24C13

**Comment by seongahjo** [comment]
@esfomeado 
You could generate `CustomJooqRecord` by `ConstructorPropertiesArbitraryIntrospector`.

You should use two options.
`pushAssignableTypeArbitraryIntrospector(CustomJooqRecord.class, ConstructorPropertiesArbitraryIntrospector.INSTANCE)`
`pushAssignableTypePropertyGenerator(CustomJooqRecord.class, new ConstructorParameterPropertyGenerator())` option.

```java
public final class ConstructorParameterPropertyGenerator implements PropertyGenerator {
	@Override
	public List<Property> generateObjectChildProperties(AnnotatedType annotatedType) {
		return PropertyCache.getConstructorProperties(annotatedType).values().stream()
			.collect(Collectors.toList());
        }

       @Override
        Property generateRootProperty(AnnotatedType annotatedType) {
		throw new UnsupportedOperationException();
	}
        
        ....
         all other methods throw UnsupportedOperationException();
}
```
